name: addSonarTag
on:
  workflow_dispatch: # Add this line to enable manual triggering
  workflow_call:
  push:
    branches:
      - main
jobs:
  tag:
    name: add tag
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Analyse Successed 
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v3
    # Commit and push all changed files.
    - name: GIT add TAG
      # Only run on main branch push (e.g. after pull request merge).
      #if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"

        # Delete all existing tags from the remote repository
        git fetch --tags
        git tag -l | grep '^Sonar' | xargs -I{} git push --delete origin {}
        
        # Generate a timestamp
        timestamp=$(date +"%Y%m%d%H%M%S")
        # Create a tag with the timestamp
        tagname="SonarPassed-$timestamp"
        
        # Create a new tag
        git tag -a "$tagname" "${{ github.sha }}" -m "${{ env.CI_COMMIT_MESSAGE }}"
        # Push the new tag to the remote repository
        git push --tags
