name: callWorkflow

on:
  workflow_dispatch:

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Call SonarQube Scan workflow
        uses: ./.github/workflows/ScanSonarGCP.yml
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
