name: callWorkflow

on:
  workflow_dispatch:

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Call SonarQube Scan workflow
        uses: ./.github/workflows/ScanSonarGCP.yml
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
