name: test Workflow

on:
  workflow_dispatch:

env:
  SONAR: ${{ secrets.SONAR }}

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: output the env var
        run: |
          echo ${{ env.SONAR }}
