name: test Workflow

on:
  workflow_dispatch:

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: output the env var
        run: |
          echo ${{ variables.SONAR_INSTANCE }}
