name: Pipeline Workflow

on:
  workflow_dispatch:

jobs:
  build-publish-artifact:
    uses: ./.github/workflows/maven-build-publish-artifact.yml

  sonarcloud-scan:
    uses: ./.github/workflows/Scan-SonarCloud.yml

  deploy-to-cloudhub:
    needs: [build-publish-artifact, sonarcloud-scan]
    if: needs.build-publish-artifact.result == 'success' && needs.sonarcloud-scan.result == 'success'
    uses: ./.github/workflows/anypointCLI-deploy-cloudhub1.yml
    secrets: inherit
