name: Pipeline Workflow

on:
  workflow_dispatch:

jobs:
  build-publish-artifact:
    uses: ./.github/workflows/maven-build-publish-artifact.yml
    secrets: inherit

  sonarqube-scan:
    uses: ./.github/workflows/ScanSonarGCP.yml
    secrets: inherit
    
  Add-sonar-tag:
    needs: [sonarqube-scan]
    uses: ./.github/workflows/addSonarTag.yml
    secrets: inherit

  deploy-to-cloudhub:
    needs: [build-publish-artifact, sonarqube-scan]
    uses: ./.github/workflows/anypointCLI-deploy-cloudhub1.yml
    secrets: inherit
